### PR TITLE
Enable Some Features on TB320FC

### PR DESCRIPTION
**Pull request by monefiera**
The file directory for enabling DT2W has been changed in TB320FC(Legion Y700/Legion Tab)'s ZUI15, so this commit has been redefined so that the "Lenovo Settings" are visible.
I also added magnetic sensor information and attempted to sleep by opening and closing the cover.

### CODE REVIEW

**Comment by phhusson** [comment]
Looks good to me, but your message is not clear:
Do those feature work properly now?

**Comment by ponces** [comment]
The fix to Hostapd that you had to include is interesting because a few days I had to revert it to be able to build this successfuly...
Another thing about this that is interesting is that on your repo you had to include the fix to be able to build the action but currently the repo is buildable as it is... I'm confused now... :/

**Comment by monefiera** [comment]
Since my fix is minor, I am considering closing Request once and resubmitting as soon as the problem is resolved... My fork can build, but I can't overwrite install to GSI(Official Project Elixir).

**Comment by ponces** [comment]
My intention was not for you to drop this... Just an heads-up regarding the build action.
Please, disreguard my comments if you have a working scenario on your side!

**Comment by monefiera** [comment]
I apologize for any concern 💦
However, my fork can only build, but can't install, so I consider it to be in a "failed" state.
Does this app (or the GSI ROM itself) have any special signature checks for TrebleApp?
If you're not too busy, [try this from my workflow](https://github.com/monefiera/treble_app/actions/runs/8727408789)...!

**Comment by monefiera** [comment]
It is a error message to try direct install TrebleApp.
I screenshot this by Zenfone 9, but I think
Screenshot_20240420-155936_Package_installer (1)
 I'm making some kind of mistake because the message appears in all environments (including non-GSI ones) that my friend and I have tried.

**Comment by phhusson** [comment]
Yeah the app is installable exclusively in GSIs.
If it's not installable in the one you're running currently, it could be using resigned keys (which is fine, and they are right for doing so). Maybe do your development on https://github.com/TrebleDroid/treble_experimentations/releases/ for the moment

**Pull request closed without merging**
