### PR TITLE
update: nubia 6 series configuration

### PR DESCRIPTION
**Pull request by boydaihungst**
What fixed: 
- dt2w (worked after this PR is merged [fix nubia 6 series dt2w + fod hbm](https://github.com/TrebleDroid/device_phh_treble/pull/35))
- Game mode
- CPU/GPU boost

What new:
- High touch sample rate
- High touch sensitivity
- Bypass charger
- Auto on/off fan while charger plugged/unplugged (also work after reboot)
- Cache boost
- UFS boost (faster read/write)
- Game mode quick setting tile. In game mode fan won't stop after charger unplugged or battery reach 100%.
- Fan control quick setting tile

Game mode / fan control tiles.
Screenshot_20231014-202214
Screenshot_20231014-202233

### CODE REVIEW

**Comment by phhusson** [comment]
Gosh that's a big one.
Overall it looks pretty good, so congrats.
Considering it's a big one, I'll need either time, or someone else to review it. Ping me again in a week if there is no news.

I do have some nits (that aren't required to be fixed to be merged):
- Is the speed of all the exec/su satisfying? I'm expecting that it should take several seconds to issue such a long list of commands, which isn't great. 
- Why canStartFan is off at 100%? I'm not sure what's the meaning of canStartFan really, can you explain it?
- The paths you're using are completely device/soc-specific, yet what you do seem pretty generic ( = setting all devfreq governors to performance, and then restoring them back). Do you think it would make sense to make it generic and just set all devfreq governors to performance? (again i'm not asking you to do it)
- Doesn't those devfreq changes collide with power hal/power hints?

**Comment by boydaihungst** [comment]
- About the exec su, currently, it will show many su prompt dialogs. If you have a better way to do so please tell me. Tbh, I'm just learning about Android system stuff in 2 weeks. 
- When the battery reached 100%, the battery would charge at a low rate. So no need fan to cool the phone anymore. Imagine we charge the phone overnight, we don't need the fan to run all the time right?  The same behavior is in stock Rom.
  - canStartFan:  If it returned `true` -> the fan can be started -> run `startFan()`; if it returned `false` -> fan need to be stopped-> run `stopFan()`
     - return true if one of these conditions is fulfilled:
         - The battery status is `BATTERY_STATUS_CHARGING` and the battery percentage is under 100% (not fully charged).
         - NOT in one of these status: `BATTERY_STATUS_DISCHARGING` || `BATTERY_STATUS_NOT_CHARGING` || `BATTERY_STATUS_UNKNOWN` || `BATTERY_STATUS_FULL`
     - NOTE: Normally, it should return `BatteryManager.BATTERY_STATUS_FULL` when the battery reaches 100%, but it doesn't, it still returns `BatteryManager.BATTERY_STATUS_CHARGING`. So I have to calculate the current battery percentage to check if it is fully charged or not (Trigger `Intent.ACTION_BATTERY_CHANGED` and get battery status from response)
     - Maybe renaming it to "isFanStartable" is better?
- Those paths are taken from this init file [vendor/etc/init/init.nubia.perf.rc](https://dumps.tadiphone.dev/dumps/nubia/nx669j-un/-/blob/qssi_NX669J-user-11-RKQ1.201105.002-nubia.20210825.104533-release-keys/vendor/etc/init/init.nubia.perf.rc). I tried to change those properties but it doesn't change cpu profile at all. And I did think about using "chmod", but it is not good to allow any apps to change devfreq governors.
- I don't understand this question. It will drain more battery, device become hotter than normal (it should be used with the fan tbh). The battery percentage still shows correctly.


Fan scenario: ( Start conditions --> [Event trigger] --> [Actions] )
- Phone powered ON && charger DISCONNECTED && battery percentage < 100% --> charger CONNECTED --> Start fan && start watching battery percentage change
- Phone powered OFF && charger CONNECTED  && battery percentage < 100% --> phone power ON --> Start fan && start watching battery percentage change

- Phone powered ON && charger CONNECTED && battery percentage < 100% -->  charger DISCONNECTED  --> Stop fan && stop watching battery percentage change
- Phone powered ON && charger CONNECTED && battery percentage < 100% -->  battery percentage == 100%  --> Stop fan && stop watching battery percentage change

**Comment by phhusson** [comment]
Ok so the idea is to have the fan on while charging because charging heats the device a lot, got it, thanks.

> About the exec su, currently, it will show many su prompt dialogs. If you have a better way to do so please tell me. 
I sadly don't have an obvious answer to this.

You can try to use Magisk's [libsu](https://github.com/topjohnwu/libsu), which supposedly doesn't depend on magisk, or didn't use to. I don't know.

You can also find some recommendations on http://su.chainfire.eu/ .
You can just build a single big command that will be executed all in just one su call

Though ideally we'd go with the prop method.

> Tbh, I'm just learning about Android system stuff in 2 weeks.
Well that's great result for 2 weeks

> Those paths are taken from this init file [vendor/etc/init/init.nubia.perf.rc](https://dumps.tadiphone.dev/dumps/nubia/nx669j-un/-/blob/qssi_NX669J-user-11-RKQ1.201105.002-nubia.20210825.104533-release-keys/vendor/etc/init/init.nubia.perf.rc). I tried to change those properties but it doesn't change cpu profile at all. And I did think about using "chmod", but it is not good to allow any apps to change devfreq governors.

Do you know why those change failed? I think it would be better to use those props if possible. Do you have logs mentioning errors (maybe selinux/audit errors) when switching those props?

> I don't understand this question. 

Okay, so in Android there is a "power" driver, which Android uses to send "hints". For instance there is a hint sent by Android to the power driver every time the touchscreen is touched or a button is pressed, to notify the "power" driver that there has been an interaction. Usually those power driver are pretty dumb, and when such an event happen they change a bunch of sysfs to match it. I'm not too sure what goes where, but for instance you can see one of your vendor config files: https://dumps.tadiphone.dev/dumps/nubia/nx669j-un/-/blob/qssi_NX669J-user-11-RKQ1.201105.002-nubia.20210825.104533-release-keys/vendor/etc/perf/targetresourceconfigs.xml write some devfreq settings.

That being said, if there is an rc script using props doing this, I'm guessing they already took this possible conflict in consideration, so let's not worry about it.

**Comment by boydaihungst** [comment]
Ah. I know why they were showing so many dialogs because It was called su 4 times in startup. From now on, It will only show 1 su prompt.

```
spListener.onSharedPreferenceChanged(sp, NubiaSettings.boostCpu)
spListener.onSharedPreferenceChanged(sp, NubiaSettings.boostGpu)
spListener.onSharedPreferenceChanged(sp, NubiaSettings.boostCache)
spListener.onSharedPreferenceChanged(sp, NubiaSettings.boostUfs)
```

**Comment by boydaihungst** [comment]
```
12-08 05:23:09.915     0     0 I init    : Parsing file /vendor/etc/init/init.nubia.perf.rc...
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 46: ParseTriggers() failed: unexported property trigger found: nubia.perf.cpu.input.boost.freq
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 48: ParseTriggers() failed: unexported property trigger found: nubia.perf.cpu.input.boost.freq
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 50: ParseTriggers() failed: unexported property trigger found: nubia.perf.cpu.input.boost.ms
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 52: ParseTriggers() failed: unexported property trigger found: nubia.perf.cpu.input.boost.ms
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 56: ParseTriggers() failed: unexported property trigger found: nubia.perf.cpu.cpufreq.ctrl
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 64: ParseTriggers() failed: unexported property trigger found: nubia.perf.cpu.boost
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 69: ParseTriggers() failed: unexported property trigger found: nubia.perf.cpu.boost
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 75: ParseTriggers() failed: unexported property trigger found: nubia.perf.gpu.boost
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 81: ParseTriggers() failed: unexported property trigger found: nubia.perf.gpu.boost
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 87: ParseTriggers() failed: unexported property trigger found: nubia.perf.gpu.boost
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 92: ParseTriggers() failed: unexported property trigger found: nubia.perf.cache.boost
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 105: ParseTriggers() failed: unexported property trigger found: nubia.perf.cache.boost
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 119: ParseTriggers() failed: unexported property trigger found: nubia.perf.gpuoc.thermalzone
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 129: ParseTriggers() failed: unexported property trigger found: nubia.perf.gpuoc.thermalzone
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 139: ParseTriggers() failed: unexported property trigger found: nubia.perf.temp.ctrl.by.cfs
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 148: ParseTriggers() failed: unexported property trigger found: nubia.perf.temp.ctrl.by.cfs
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 156: ParseTriggers() failed: unexported property trigger found: nubia.perf.ufs
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 158: ParseTriggers() failed: unexported property trigger found: nubia.perf.ufs
12-08 05:23:09.915     0     0 E init    : /vendor/etc/init/init.nubia.perf.rc: 166: ParseTriggers() failed: unexported property trigger found: nubia.perf.vd.created
12-08 05:23:09.915     0     0 I init    : Parsing file /vendor/etc/init/init.nubia.widevine.rc...

```
This is from logcat

**Comment by boydaihungst** [comment]
https://android.googlesource.com/platform/system/core/+/master/init/action_parser.cpp#73
https://android.googlesource.com/platform/system/core/+/master/init/action_parser.cpp#39

Look like "nubia.perf." doesn't in the `kPartnerPrefixes`, so it will be rejected.

**Comment by boydaihungst** [comment]
Added "nubia.perf." to the `kPartnerPrefixes` list and prop action was triggered and the governor changed successfully.
I guess I need to create a pull request for this [platform_system_core](https://github.com/TrebleDroid/platform_system_core/) or create a git patch file. I wonder where you place git patch files? Or did it auto-generate from git merge commits? 😃

**Comment by phhusson** [comment]
Merged

**Pull request closed without merging**
