### PR TITLE
RE:Enable Some Features on TB320FC

### PR DESCRIPTION
**Pull request by monefiera**
This is a resubmission of a previous pull-request with a different branch. ~~All files are unchanged.~~
As I'm new to writing this type of code, there may be fatal errors. I would appreciate it if someone with more knowledge could verify this.

(1st write at 2024/04/18)The file directory for enabling DT2W has been changed in TB320FC(Legion Y700/Legion Tab)'s ZUI15, so this commit has been redefined so that the "Lenovo Settings" are visible.
I also added magnetic sensor information and attempted to sleep by opening and closing the cover.

### CODE REVIEW

**Comment by monefiera** [comment]
Tested with the real device in the main unit and confirmed that this works.
As for Lenovo.kt, I have reverted it back. However, I have left the directory of files that are switches as a note and will ask someone who can implement it (I could not figure out how to define multiple directory in val dtPanel).

**Comment by phhusson** [comment]
I need to merge it manually because of the commit mess (or you could rebase // remove the hostapd chanmge), but it's good I'll merge it today

**Comment by monefiera** [comment]
Should I also revert the Hostapd.kt changes to marge?

**Comment by phhusson** [comment]
No I'll do it

**Comment by monefiera** [comment]
okey, thx so much!

**Comment by phhusson** [comment]
Done

**Pull request closed without merging**
