### PR TITLE
Enable SYSBTA by default

### PR DESCRIPTION
**Pull request by ChonDoit**
We need it nowadays

Also, change Checkboxes with Switches

### CODE REVIEW

**Comment by ponces** [comment]
Just to make, would it make sense to also change [this ](https://github.com/TrebleDroid/treble_app/blob/5db8d33337636e239d65740926b3ea55b7d931dc/app/src/main/java/me/phh/treble/app/Misc.kt#L215)to "true"?

**Comment by ponces** [comment]
What if the value saved is one that the `getBoolean` can't get for some reason? It would be false in that case, wouldn't it?

**Comment by ChonDoit** [comment]
> What if the value saved is one that the `getBoolean` can't get for some reason? It would be false in that case, wouldn't it?

Yes, but I guess this will not be the only broke thing on such scenario. Anyways, we can change it "just in case"

**Comment by ChonDoit** [comment]
Just to clarify, from my side I prefer to leave as it. If it's broken we will notice quickly

**Comment by ponces** [comment]
> Just to clarify, from my side I prefer to leave as it. If it's broken we will notice quickly

Then do as you prefer :)

**Pull request merged**
